---

- name: Basic midolman.conf
  template: src=midolman.conf.j2 dest=/etc/midolman/midolman.conf owner=root group=root

- name: Apply host template (this node only)
  shell: mn-conf template-set -h local -t "{{ agent_template }}"
  retries: 5
  delay: 10

- name: Create midonetrc
  template: src=midonetrc.j2 dest=/root/.midonetrc owner=root group=root
  become: yes
  notify:
    - Restart midolman
