---

- name: Basic midolman.conf
  template: src=midolman.conf.j2 dest=/etc/midolman/midolman.conf owner=root group=root

- name: Apply host template (this node only)
  shell: mn-conf template-set -h local -t "{{ agent_template }}"
  retries: 5
  delay: 10

- name: Create midonetrc
  ini_file: dest=/root/.midonetrc section=cli option={{ item.option }} value={{ item.value }}
  with_items:
    - { option: 'api_url', value: "http://{{ midonet_api_hostname }}:{{ midonet_api_port }}/midonet-api" }
    - { option: 'username', value: '{{ midonet_username }}' }
    - { option: 'password', value: "{{ midonet_password }}" }
    - { option: 'project_id', value: '{{ midonet_project }}' }
  notify:
    - Restart midolman
