---

- name: Install Midolman
  yum: name={{ item }} state=present
  with_items:
    - midolman
    - python-midonetclient

- name: Install MEM jmxscraper
  yum: name=midonet-jmxscraper state=present
  when: mem_jmxscraper
